-- MySQL Script generated by MySQL Workbench
-- mar. 14 déc. 2021 22:18:41 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

CREATE SCHEMA IF NOT EXISTS `schema_poc` DEFAULT CHARACTER SET utf8 ;
USE `schema_poc` ;

-- -----------------------------------------------------
-- Table `mydb`.`bloc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloc` (
  `id_bloc` INT NOT NULL,
  `bloc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_bloc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competences` (
  `id_competence` INT NOT NULL,
  `competence` VARCHAR(45) NOT NULL,
  `id_bloc` INT NOT NULL,
  PRIMARY KEY (`id_competence`, `id_bloc`),
  INDEX `fk_competences_bloc1_idx` (`id_bloc` ASC),
  CONSTRAINT `fk_competences_bloc1`
    FOREIGN KEY (`id_bloc`)
    REFERENCES `bloc` (`id_bloc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`niveaux`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `niveaux` (
  `id_niveau` INT NOT NULL,
  `val_niveau` INT NOT NULL,
  `desc_niveau` VARCHAR(45) NULL,
  PRIMARY KEY (`id_niveau`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`utilisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `utilisateurs` (
  `id_utilisateur` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `url_photo` VARCHAR(45) NULL,
  `passwd` VARCHAR(45) NOT NULL,
  `identifiant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_utilisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competences_utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competences_utilisateur` (
  `id_utilisateur` INT NOT NULL,
  `id_competence` INT NOT NULL,
  `id_niveau` INT NOT NULL,
  `id_bloc` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`, `id_competence`, `id_niveau`),
  INDEX `fk_competences_utilisateur_niveaux1_idx` (`id_niveau` ASC),
  INDEX `fk_competences_utilisateur_utilisateurs1_idx` (`id_utilisateur` ASC),
  INDEX `fk_competences_utilisateur_competences1_idx` (`id_competence` ASC),
  CONSTRAINT `fk_competences_utilisateur_niveaux1`
    FOREIGN KEY (`id_niveau`)
    REFERENCES `niveaux` (`id_niveau`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competences_utilisateur_utilisateurs1`
    FOREIGN KEY (`id_utilisateur`)
    REFERENCES `utilisateurs` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competences_utilisateur_competences1`
    FOREIGN KEY (`id_competence`)
    REFERENCES `competences` (`id_competence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
